/*
 * Resampler.h
 * -----------
 * Purpose: Holds the tables for all available resamplers.
 * Notes  : (currently none)
 * Authors: OpenMPT Devs
 * The OpenMPT source code is released under the BSD license. Read LICENSE for more details.
 */

#pragma once

#include "openmpt/all/BuildSettings.hpp"


#ifdef MODPLUG_TRACKER
#include "WindowedFIR.h"
#endif
#include "Mixer.h"
#include "MixerSettings.h"
#include "Paula.h"


OPENMPT_NAMESPACE_BEGIN


#ifdef LIBOPENMPT_BUILD
// All these optimizations are not applicable to the tracker
// because cutoff and firtype are configurable there.

// Cache resampler tables across resampler object creation.
// A C++11-style function-static singleton is holding the cached values.
#define MPT_RESAMPLER_TABLES_CACHED

// Prime the tables cache when the library is loaded.
// Caching gets triggered via a global object that primes the cache during
//  construction.
// This is only really useful with MPT_RESAMPLER_TABLES_CACHED.
#ifdef MPT_BUILD_FUZZER
#define MPT_RESAMPLER_TABLES_CACHED_ONSTARTUP
#endif

#endif // LIBOPENMPT_BUILD


#define SINC_WIDTH       16

#define SINC_PHASES_BITS 14
#define SINC_PHASES      (1<<SINC_PHASES_BITS)

#ifdef MPT_INTMIXER
using SINC_TYPE = int16;
#define SINC_QUANTSHIFT 15
#else
using SINC_TYPE = mixsample_t;
#endif // MPT_INTMIXER

#define SINC_MASK (SINC_PHASES-1)
static_assert((SINC_MASK & 0xffff) == SINC_MASK); // exceeding fractional freq

// Shared mip level count: 8 octave-spaced tables covering 1x–128x downsample.
// Every mipped mode uses trilinear blend between adjacent levels via log2(ratio).
#define MIP_LEVELS 8

// 64-tap anisotropic sinc tables (Quinlight Aniso-64 mode)
#define SINC_WIDTH_64       64
#define SINC_PHASES_64_BITS 16
#define SINC_PHASES_64      (1 << SINC_PHASES_64_BITS)  // 65536
#define SINC_MASK_64        (SINC_PHASES_64 - 1)

// 8-tap sinc mip (SINC8 / FIR mode)
#define SINC8_WIDTH         8
#define SINC8_PHASES_BITS   12
#define SINC8_PHASES        (1 << SINC8_PHASES_BITS)    // 4096
#define SINC8_MASK          (SINC8_PHASES - 1)

// 4-tap sinc mip (shared: Cubic + Catmull-Rom)
#define TAP4_WIDTH          4
#define TAP4_PHASES_BITS    12
#define TAP4_PHASES         (1 << TAP4_PHASES_BITS)     // 4096
#define TAP4_MASK           (TAP4_PHASES - 1)

// 2-tap sinc mip (Linear)
#define TAP2_WIDTH          2
#define TAP2_PHASES_BITS    12
#define TAP2_PHASES         (1 << TAP2_PHASES_BITS)     // 4096
#define TAP2_MASK           (TAP2_PHASES - 1)


class CResamplerSettings
{
public:
	ResamplingMode SrcMode = Resampling::Default();
#ifdef MODPLUG_TRACKER
	double gdWFIRCutoff = 0.97;
	uint8 gbWFIRType = WFIR_KAISER4T;
#endif
	Resampling::AmigaFilter emulateAmiga = Resampling::AmigaFilter::Off;
	double aniso64_k_beta = 0.65;   // 1st-order β-shear velocity weight
	double aniso64_k_beta2 = 0.15;  // 2nd-order β-shear acceleration weight
public:
	constexpr CResamplerSettings() = default;
	bool operator == (const CResamplerSettings &cmp) const
	{
#if MPT_COMPILER_CLANG
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wfloat-equal"
#endif // MPT_COMPILER_CLANG
		return SrcMode == cmp.SrcMode && emulateAmiga == cmp.emulateAmiga && aniso64_k_beta == cmp.aniso64_k_beta && aniso64_k_beta2 == cmp.aniso64_k_beta2
#ifdef MODPLUG_TRACKER
			&& gdWFIRCutoff == cmp.gdWFIRCutoff && gbWFIRType == cmp.gbWFIRType
#endif
			;
#if MPT_COMPILER_CLANG
#pragma clang diagnostic pop
#endif // MPT_COMPILER_CLANG
	}
	bool operator != (const CResamplerSettings &cmp) const { return !(*this == cmp); }
};


class CResampler
{
public:
	CResamplerSettings m_Settings;
#ifdef MODPLUG_TRACKER
	CWindowedFIR m_WindowedFIR;
	static const int16 FastSincTable[256 * 4];
#endif

#ifdef MODPLUG_TRACKER
	static bool StaticTablesInitialized;
	#define RESAMPLER_TABLE static
#else
	// no global data which has to be initialized by hand in the library
	#define RESAMPLER_TABLE 
#endif // MODPLUG_TRACKER

	RESAMPLER_TABLE Paula::BlepTables blepTables;               // Amiga BLEP resampler

	// Mip chains: octave-spaced Kaiser sinc tables with trilinear LOD blending.
	// Each mode's tables are generated by getsinc_n() at its native tap width.
	// log2(ratio) selects adjacent levels; fractional part drives trilinear blend.
	alignas(64) RESAMPLER_TABLE SINC_TYPE gAniso64Mip[MIP_LEVELS][SINC_PHASES_64 * SINC_WIDTH_64];  // 256 MB
	RESAMPLER_TABLE SINC_TYPE gPolyphaseMip[MIP_LEVELS][SINC_PHASES * SINC_WIDTH];                   // 16 MB
	RESAMPLER_TABLE SINC_TYPE gSinc8Mip[MIP_LEVELS][SINC8_PHASES * SINC8_WIDTH];                     //  2 MB
	RESAMPLER_TABLE SINC_TYPE g4TapMip[MIP_LEVELS][TAP4_PHASES * TAP4_WIDTH];                        //  1 MB
	RESAMPLER_TABLE SINC_TYPE gLinearMip[MIP_LEVELS][TAP2_PHASES * TAP2_WIDTH];                       // 0.5 MB

	bool m_hasAVX = false;    // Runtime CPUID check for AVX (without FMA)
	bool m_hasAVX2 = false;   // Runtime CPUID check for AVX2+FMA3
	bool m_hasAVX512 = false; // Runtime CPUID check for AVX-512F+VL

#undef RESAMPLER_TABLE

private:
	CResamplerSettings m_OldSettings;
public:
	CResampler(bool fresh_generate=false)
	{
		if(fresh_generate)
		{
			InitializeTablesFromScratch(true);
		} else
		{
			InitializeTables();
		}
	}
	void InitializeTables()
	{
		#if defined(MPT_RESAMPLER_TABLES_CACHED)
			InitializeTablesFromCache();
		#else
			InitializeTablesFromScratch(true);
		#endif
	}
	void UpdateTables()
	{
		InitializeTablesFromScratch(false);
	}

private:
	void InitializeTablesFromScratch(bool force=false);
#ifdef MPT_RESAMPLER_TABLES_CACHED
	void InitializeTablesFromCache();
#endif
};


OPENMPT_NAMESPACE_END
